# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dd26a8cdf8adb42665c7322d4f37ad92473749b2bab812dc0991f586bd7350edfce8c88b0e11c5243826a89cd1ee90f1cfc17f73f51e7b208fef3b0d1fd42ed

test:
  secret_key_base: dae8468fe0e3fd52a81d7c072e473208238f37700b8f89d51f0ac927b718d65f024f2dce2bd619fbac59c16698be1fdbe0d1d3aaf02d4688a9594bd926d340f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
